export const SETCOORDIN = 'SETCOORDIN';
export const SETFILEIN = 'SETFILEIN';
export const SETDISPLAYONMAP = 'SETDISPLAYONMAP';
export const SETMAPDISTANCE = 'SETMAPDISTANCE';
export const READDATA = 'READDATA';
export const DATACOMPLETE = 'DATACOMPLETE';
export const PREPROCESSDATA = 'PREPROCESSDATA';
