name: Install NPM dependecies Workflow

on:
  workflow_call:

jobs:
  npm-install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get directories paths
        id: dirs
        run: |
          echo "npm-cache-dir=$(npm config get cache)" >> $GITHUB_OUTPUT
          echo "node-modules-dir=**/node_modules" >> $GITHUB_OUTPUT

      - name: Cache NPM packages
        uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ${{ steps.dirs.outputs.npm-cache-dir }}
            ${{ steps.dirs.outputs.node-modules-dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
