name: Release NPM app

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    if: startsWith(github.event.head_commit.message, 'fix:') || startsWith(github.event.head_commit.message, 'feat:') || startsWith(github.event.head_commit.message, 'refactor:')

    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get NPM cache directory path
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache NPM packages
        uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Prepare for version bump
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com

      - name: Bump patch version
        if: startsWith(github.event.head_commit.message, 'fix:')
        run: npm version patch

      - name: Bump minor version
        if: startsWith(github.event.head_commit.message, 'feat:')
        run: npm version minor

      - name: Bump major version
        if: startsWith(github.event.head_commit.message, 'refactor:')
        run: npm version major
